api extractor: Don't try to "set" & "list"
TypeError: unsupported operand type(s) for &: 'set' and 'list'

Caused by c1da24de09abc3d68275524caefbbb5666309ad2